Repository altlinux/admx-basealt, pull requests merged in 2020-09, with the labels that each got.

#23 Fix duplicate naming (Accounts service)
  en-US/basealtsystemdunits.adml
  ru-RU/basealtsystemdunits.adml
Labels: invalid

#24 NTP Applier switch added
  BaseALTGroupPolicies.admx
  en-US/basealtgrouppolicies.adml
  ru-RU/basealtgrouppolicies.adml
Labels: enhancement

#25 Add sshd-allow-groups-list
  BaseALTControl.admx
  en-US/basealtcontrol.adml
  ru-RU/basealtcontrol.adml
Labels: enhancement, invalid
